repositories:
  leethomason/tinyxml2:
    type: git
    url: https://github.com/leethomason/tinyxml2.git
    version: master
  foonathan/foonathan_memory:
    type: git
    url: https://github.com/foonathan/memory.git
    version: main
  gabime/spdlog:
    type: git
    url: https://github.com/gabime/spdlog.git
    version: master
  jbeder/yaml-cpp:
    type: git
    url: https://github.com/jbeder/yaml-cpp.git
    version: 0f9a586ca1dc29c2ecb8dd715a315b93e3f40f79