name: Build All

on: [push, pull_request]

jobs:
  build-arm:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ros2arm
      ANDROID_ABI: armeabi-v7a
      ARTIFACT_NAME: ros2-arm
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: |
        docker build . -t ${IMAGE_NAME} --build-arg ANDROID_ABI=${ANDROID_ABI}
    - name: Make artifact
      run: |
        docker run --rm -v $PWD:/ros2 ${IMAGE_NAME} bash -c "cp -r /ros2_ws/install /ros2"
        mv install ${ARTIFACT_NAME}
        tar -zcf ${ARTIFACT_NAME}.tar.gz ${ARTIFACT_NAME}
    - uses: actions/upload-artifact@v2
      with:
        name: ${ARTIFACT_NAME}
        path: ${ARTIFACT_NAME}.tar.gz
  build-arm64:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ros2arm64
      ANDROID_ABI: arm64-v8a
      ARTIFACT_NAME: ros2-arm64
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: |
        docker build . -t ${IMAGE_NAME} --build-arg ANDROID_ABI=${ANDROID_ABI}
    - name: Make artifact
      run: |
        docker run --rm -v $PWD:/ros2 ${IMAGE_NAME} bash -c "cp -r /ros2_ws/install /ros2"
        mv install ${ARTIFACT_NAME}
        tar -zcf ${ARTIFACT_NAME}.tar.gz ${ARTIFACT_NAME}
    - uses: actions/upload-artifact@v2
      with:
        name: ${ARTIFACT_NAME}
        path: ${ARTIFACT_NAME}.tar.gz
    # - name: Login to DockerHub
    #     uses: docker/login-action@v1
    #     with:
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_PASSWORD }}
    #   - name: Push image
    #     uses: docker/build-push-action@v2
    #     with:
    #       push: true
    #       tags: |
    #         ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:latest